### ISSUE TITLE
Consistency in setting environments.

### ISSUE THREAD

**Issue by Hypercubed** [docpad/docpad#669] opened 2013-10-06 10:00 UTC
In order to disable dynamic pages you need to specify the environment as `static`.  In order to enable static page redirects in the clean-url plugin you need to specify the environment as `static`.  In order to enable livereload you need to specify the environment as `development`.  Other plugins do different things depending on weather the environment includes static or development.  These are not consistent nor configurable.  In addition when I create an additional environment in my config I need to specify the environment as `mystaticsnv,static` or `mydevenv,development`.  Should I be able to specify a new environment as static or development?

**Comment by balupton** [comment] 2018-07-20 15:51
Possible dupe of #1045

**Closed by balupton** 2018-07-20 15:51 UTC
