### ISSUE TITLE
Error running docpad: spawn EACCES

### ISSUE THREAD

**Issue by cbroome** [docpad/docpad#944] opened 2015-03-22 13:04 UTC
I'm running Docpad v6.78 on a Macbook. After running a `docpad update` I started getting the following error consistently: 

```
$ docpad generate
An error occured within the child DocPad instance: spawn EACCES
```

Going back to version 6.75 seems to have resolved the issue. Has anyone else seen this?

**Comment by balupton** [comment] 2015-03-22 16:16
Hey @cbroome, you you provide the output of `docpad generate -d`, as well as the output of `docpad generate -d --global`

**Comment by cbroome** [comment] 2015-03-22 16:58
I upgraded back to the current release using: `$docpad upgrade; docpad update` and the error persisted. `docpad generate -d` returned the same error as above, but the output for `docpad generate -d --global` was fairly large. Is there a way to attach a text file? It was about 1.3 mbs in size.

**Comment by balupton** [comment] 2015-03-22 17:08
Before proceeding further, do you use sudo at all with node or npm?

**Comment by cbroome** [comment] 2015-03-22 17:08
No, running as a regular user

**Comment by cbroome** [comment] 2015-03-22 17:14
It does look like `docpad generate -d --global` hangs at a certain point, right after a bunch of 

```
debug: track runner ➞  track task > added
    → [2015-03-22 13:10:26.740] [events.js:95] [_Class.emit]
```
The last command to run was: 

``` 
debug: render tasks for: index.html.eco ➞  renderExtensions: index.html.eco > done
    → [2015-03-22 13:10:19.199] [events.js:95] [_Class.emit]
debug: Emitted the event: render
    → [2015-03-22 13:10:19.204] [events.js:180] [TaskGroup.g]
debug: track runner ➞  track task > added
    → [2015-03-22 13:10:19.215] [events.js:95] [_Class.emit]
```
I also have a habit of adding `.eco` to the end of all my post files. Generally there are just warnings, but with the most recent version they look more like stack traces.

**Comment by astericky** [comment] 2015-03-23 01:35
I am having this same issue.

**Comment by balupton** [comment] 2015-03-27 15:28
No clue what could be causing this.

**Comment by astericky** [comment] 2015-03-28 04:00
Yes. I will post in just a bit.

**Comment by astericky** [comment] 2015-03-28 19:04
I currently have node v0.12.0 and npm 2.7.3 installed on my machine. 

I followed the instructions located here ==> https://docpad.org/docs/install

I was able to "successfully" install docpad without needing to use sudo. However, when I created a new folder as they advise here ==> https://docpad.org/docs/begin ; what ends up happening is I get a message that says the following:

info: Installed the skeleton succesfully
notice: Shutting down the global DocPad, and starting up the local

as the last two messages I get when I type 'docpad run' in the folder that I plan to use for the docpad site as recommended. Then it goes back to the command prompt. When I try to run 'docpad run' again I get an error that says the following:

An error occured within the child DocPad instance: spawn EACCES

Thanks again for responding everyone. I certainly appreciate any help you all can provide. :-)~

**Comment by balupton** [comment] 2015-03-29 02:50
@astericky possibly related to https://github.com/bevry/safeps/pull/5

**Comment by balupton** [comment] 2015-03-29 02:53
@astericky thanks for that, I'll add some debugging code to the relevant area:
https://github.com/docpad/docpad/blob/d14b514ce506aa7c178a94e5a5c7e1cf8b77e8e9/src/lib/util.coffee#L74-L98

**Comment by alexwoehr** [comment] 2015-04-17 03:35
OK, just some thoughts here.

### My experience

Hey, interestingly enough, I ran into the "Spawn: EACCES" issue on Linux (NOT mac osx). It turned out to be a problem with how I had node installed. Everything was actually broken.

I was using the simple nave script, which has gotten out of date (it seems to me). To fix node, I had to switch to NVM.

### The short answer

I suspect this is probably an OS or environment setup issue that you are experiencing, instead of a docpad specific issue.

You may need to start with a fresh setup of node or NVM. (Do you use a version manager? What manager do you use?)

### The long answer

The issue is discussed a little bit in the following gist. [Here is one specific comment talking about it.](https://gist.github.com/isaacs/579814#comment-6435)

I am guessing that this may not apply directly to the Mac issues. However, it could be a similar kind of issue: the environment is not setup correctly on OS X, just as my environment and permissions were incorrect.

If a new environment does not solve the problem, it may be good to dump the syscalls that caused the error.

Of course, EACCES is an error reported by the kernel / filesystem. I am a sysadmin these days, and I use linux strace to debug weird OS errors all the time. ("strace all the things!!!") The mac equivalent is dtruss. Basically, strace/dtruss/truss command dumps all the system calls that are run by the process. You can see the EACCES error and you can see it bubbling up to the main process (mixed up with a lot of job control baggage).

Maybe if @cbroome & @astericky could use the dtruss command to show what's happening?

I think something like this could work for mac:
```bash
dtruss -f docpad generate 2> dtruss.txt
```

That will generate a large dump of all filesystem and process control operations that were executed. It is possible to then zero in on the error and see what was happening and what triggered the error happened.

You may need to private message the results somehow, instead of just dropping it in a gist. (E.g., if any child processes read /etc/passwd for some reason, the first couple lines would show up in the dtruss output.)

I was running:
```bash
strace  -f ./node_modules/.bin/docpad --help  2>strace.txt
```

and then I could look at strace.txt and follow through the EACCES error and find out where stuff broke.

**Comment by cbroome** [comment] 2015-04-17 13:20
Truth be told, I used the instructions from the docpad site--https://docpad.org/docs/install--for both computers where I saw the issue. That means setting up through NVM as detailed here: https://learn.bevry.me/node/install

I see about running the other commands in the next day or two

**Comment by astericky** [comment] 2015-04-17 23:45
@alexwoehr ,
 dtruss -f docpad generate 2> dtruss.txt is telling me I needed additional privileges to use it.

**Comment by tvjames** [comment] 2015-04-22 04:38
I've also ran into this problem, regardless of the version of docpad i was attempting to use (local or global). Instrumented my global copy until i was able to chase it down. On OS X Yosemite, using the standard node+npm installer package, npm run as sudo. Was able to get it working by supplying the full path to node (of note, node is in the path as well): 

Changing (https://github.com/docpad/docpad/blob/d14b514ce506aa7c178a94e5a5c7e1cf8b77e8e9/src/lib/util.coffee#L87): 

```
	# Spawn Local DocPad Executable
	startLocalDocPadExecutable: (next) ->
		args = process.argv.slice(2)
		command = ['node', docpadUtil.getLocalDocPadExecutable()].concat(args)
		return require('safeps').spawn command, {stdio:'inherit'}, (err) ->
			if err
				if next
					next(err)
				else
					message = 'An error occured within the child DocPad instance: '+err.message+'\n'
					docpadUtil.writeStderr(message)
			else
				next?()
```

To: 

```
	# Spawn Local DocPad Executable
	startLocalDocPadExecutable: (next) ->
		args = process.argv.slice(2)
		command = ['/usr/local/bin/node', docpadUtil.getLocalDocPadExecutable()].concat(args)
		return require('safeps').spawn command, {stdio:'inherit'}, (err) ->
			if err
				if next
					next(err)
				else
					message = 'An error occured within the child DocPad instance: '+err.message+'\n'
					docpadUtil.writeStderr(message)
			else
				next?()
```

**Comment by balupton** [comment] 2015-04-22 05:32
@tvjames strange, as safeps should detect that path automatically. Inside one of your docpad website directories, can you do:

```
cd ./node_modules/docpad/
node -e "require('safeps').getExecPath('node', console.log)"
```

And post the output

**Comment by tvjames** [comment] 2015-04-22 06:08
Can do.

Output:

```
$ node -e "require('safeps').getExecPath('node', console.log)"
null '/usr/local/bin/node'
```

**Comment by balupton** [comment] 2015-04-22 07:38
@tvjames baffling, as that detected the same path as what you replaced it with.

`safeps.spawn` by default, should run `safeps.getExecPath` on the first argument and if a result is returned, it should use the result instead: https://github.com/bevry/safeps/blob/320a4c414389270e8f0f47d2f43e81217fb3b991/src/lib/safeps.coffee#L270-L276

So very strange such a replacement works. The only thing I can think of, is either that code isn't being reached, or for some reason, that code is failing there or now being applied properly.

**Comment by tvjames** [comment] 2015-04-22 22:56
Interestingly adding `safe: false` to the opts for spawn also gets it to work without changing the path. https://github.com/docpad/docpad/blob/d14b514ce506aa7c178a94e5a5c7e1cf8b77e8e9/src/lib/util.coffee#L90

**Comment by andyj** [comment] 2015-05-20 21:22
I had this trouble tonight, I am using NVM and Node v0.10.30. 

I ended up just re-running the NVM install script and all seemed to work fine for me. 

````curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.2/install.sh | bash````

**Comment by mikeumus** [comment] 2016-03-31 05:07
My story for this error began when it showed in a DocPad project I didn't work on for a month or so in Cloud9 IDE. 

I did `docpad run` and it was giving this error. I used NVM to jump to Node v5.9.1, but `docpad run` was still giving the error so I tried `sudo docpad run` and it showed I needed to run **`npm rebuild node-sass`**.

 I did that but `docpad run` still gave the error, **`sudo docpad run`** got the DocPad server running successfully.

**Comment by fizzvr** [comment] 2016-07-08 18:57
I got this error, but we run docpad with flag `-- global ` as normally. So i think this is no Docpad issue but I testing my npm modules in other DIRECTORY and I got the stuck.. :( [fixing-npm-permissions](https://docs.npmjs.com/getting-started/fixing-npm-permissions) :ghost:

**Comment by balupton** [comment] 2018-07-20 14:34
Closing due to age.

**Closed by balupton** 2018-07-20 14:34 UTC
Labels: type support / question
