### ISSUE TITLE
can't run docpad

### ISSUE THREAD

**Issue by magrawala** [docpad/docpad#1084] opened 2018-08-02 22:12 UTC
I'm getting the following error when do a docpad run (Any ideas how to resolve?):

docpad run
/Users/maneesh/development/testCode/docpad-sites/maneesh-homepage/node_modules/docpad/node_modules/editions/es2015/index.js:186
        throw new DetailedError('There are no suitable editions for this environment:', { opts: opts, editions: editions, failures: editionFailures });

**Comment by balupton** [comment] 2018-08-17 08:35
dupe of #1085

**Closed by balupton** 2018-08-17 08:35 UTC
