### ISSUE TITLE
Metadata not updated when property is deleted

### ISSUE THREAD

**Issue by dimitarkolev** [docpad/docpad#929] opened 2015-02-19 12:15 UTC
I noticed a strange behavior when having a property in the document metadata and delete it. It is not deleted from the metadata until the next regeneration.
This is not a major issue but may lead to unexpected behavior.

**Comment by balupton** [comment] 2018-09-06 19:37
More details at https://github.com/docpad/docpad/issues/980

**Comment by balupton** [comment] 2018-09-06 19:38
Closing as dupe of #588

**Closed by balupton** 2018-09-06 19:38 UTC
Labels: affects metadata

**Comment by balupton** [comment] 2018-09-06 19:41
Closing as dupe of #521

**Comment by balupton** [comment] 2018-09-06 19:42
Closing as dupe of #517
