### ISSUE TITLE
Metadata not properly cleared on reload

### ISSUE THREAD

**Issue by Ziflin** [docpad/docpad#980] opened 2015-06-03 03:06 UTC
I had some logic based on a metadata tag and noticed that if the tag wasn't being removed between reloads.  To reproduce:
- docpad run
- Set a metadata value in say "index.html.md"
  - test: "Hello"
- in a layout file, say "default.html.eco"
  - ....
  - <%= @document.test %>
  - ...
- Save and refresh the browser.
- Remove: _test: "Hello"_ and resave and refresh the browser.  It will still display the **old** _test_ value.

You must manually stop (ctrl-c) and restart docpad run to have it properly render without the old test value.  This caused me a few WTF moments :). It looks like docpad is caching the yaml/metadata values instead of properly clearly them each reload.

**Comment by dimitarkolev** [comment] 2015-06-09 08:02
This bug is the same as #929

**Comment by fizzvr** [comment] 2015-06-10 17:16
Agree :-1: 
>  This caused me a few WTF moments :).

**Comment by balupton** [comment] 2018-09-06 19:38
Closing as dupe of #929

**Closed** 2018-09-06 19:38 UTC
Labels: affects metadata, type suggestion / proposal, type support / question

**Comment by balupton** [comment] 2018-09-06 19:40
Closing as dupe of #521

**Comment by balupton** [comment] 2018-09-06 19:42
Closing as dupe of #517
