### ISSUE TITLE
`ignored: true` documents are showing up in collections

### ISSUE THREAD

**Issue by robhawkes** [docpad/docpad#807] opened 2014-02-18 10:11 UTC
Not sure exactly what version triggered this behaviour, but at least in 6.63, `ignore: true` has stopped ignoring files – they generate into the out directory.

This has already resulted in near-embarrassment as draft articles have been published without my knowledge or permission.

Any idea why this is happening?

**Comment by balupton** [comment] 2018-07-20 16:25
Possible dupe of https://github.com/docpad/docpad/issues/392

**Closed by balupton** 2018-07-20 16:25 UTC
Labels: 1 - confirmed, affects core, difficulty days, patches welcome, type defect
