### ISSUE TITLE
Queryengine live collections don't recalculate correctly on livereload when meta-data property it depends on is removed.

### ISSUE THREAD

**Issue by gebrits** [docpad/docpad#588] opened 2013-08-07 11:08 UTC
A Queryengine live collection fails to recalculate correctly using livereload when a meta-data property on which it's calculation depends is removed.

Best explained with an example: 

in docpad.coffee I have a collection 'pagesInMainMenu' calculated based on the queryengine, see: 
https://gist.github.com/clearskyabove/6173100

This extend the 'pages' collection found in the example to check whether to include a page in the main menu. This depends on a meta-data tag 'includenInNavs' in a post, e.g:

 `includenInNavs: ['main', 'sidebar']`

The collection checks if 'main' is contained in the array.

Problem:
- 'pagesInMainMenu'-collection updates correctly when the meta-data property 'includeInNavs' is changed to a different value. 
- However, 'pagesInMainMenu'-collection DOESN'T update correctly when the meta-data property 'includeInNavs' is removed completely.

Thanks, 
Geert-Jan

**Comment by balupton** [comment] 2018-09-06 19:39
Closing as dupe of #521

**Closed by balupton** 2018-09-06 19:39 UTC
Labels: affects metadata

**Comment by balupton** [comment] 2018-09-06 19:41
Closing as dupe of #521

**Comment by balupton** [comment] 2018-09-06 19:42
Closing as dupe of #517
