### ISSUE TITLE
docpad-plugin-babel: TypeError: Class constructor BasePlugin cannot be invoked without 'new'

### ISSUE THREAD

**Issue by topherfangio** [docpad/docpad#1089] opened 2018-09-01 01:35 UTC
Hi all,

Just getting back into DocPad after a while without it and I'm running into a bit of an issue. I actually hit https://github.com/docpad/docpad/issues/1087 first and thus downgraded to version 6.80.0 which fixed my problem with DocPad hanging, but I'm now getting the following error:

```bash
TypeError: Class constructor BasePlugin cannot be invoked without 'new'
    at new BabelPlugin (/Users/topherfangio/Documents/Development/etison/devdocs/node_modules/docpad-plugin-babel/out/babel.plugin.js:13:48)
    at PluginLoader.create (/usr/local/lib/node_modules/docpad/esnext/lib/plugin-loader.js:260:26)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:3595:29
    at PluginLoader.load (/usr/local/lib/node_modules/docpad/esnext/lib/plugin-loader.js:240:7)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:3590:27
    at PluginLoader.unsupported (/usr/local/lib/node_modules/docpad/esnext/lib/plugin-loader.js:146:7)
    at /usr/local/lib/node_modules/docpad/esnext/lib/docpad.js:3568:25
    at success (/usr/local/lib/node_modules/docpad/esnext/lib/plugin-loader.js:71:16)
    at safefs.readFile.error (/usr/local/lib/node_modules/docpad/esnext/lib/plugin-loader.js:110:18)
    at /usr/local/lib/node_modules/docpad/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)
```

Downgrading to version 6.79.0 seems to fix this, so I assume it was a recent change that made the babel plugin incompatible.

I'm happy to dig in a bit and see if I can help with this, and/or submit a PR to the babel plugin if needed, just need to know how I can be most helpful!

**Comment by balupton** [comment] 2018-09-03 12:05
Refer to:

- https://github.com/docpad/docpad/blob/master/HISTORY.md#v6800-beta-2018-march-7
- https://github.com/docpad/docpad/issues/1076

For details. The issue is that docpad-plugin-babel is a CoffeeScript v1 plugin, and needs to be updated to CoffeeScript v2. This can be done by the plugin author running [boundation](https://github.com/bevry/boundation) on it.

If they want the docpad team to do it, then transferring docpad-plugin-babel to github.com/docpad and running:

- `npm owner add balupton docpad-plugin-babel`
- `npm owner add bevryme docpad-plugin-babel`

**Closed** 2018-09-03 12:11 UTC
Labels: affects plugin, type defect

**Comment by RichardBray** [comment] 2020-10-27 11:04
Does anyone have a concrete answer for this issue? I'm currently facing it and there doesn't seem to be a surefire fix.

**Comment by balupton** [comment] 2020-10-27 19:02
@RichardBray https://github.com/docpad/docpad-plugin-babel/issues/9#issuecomment-669838085
